DROP TABLE IF EXISTS comments
CASCADE;

CREATE TABLE comments
(
    id SERIAL PRIMARY KEY,
    comment VARCHAR(300) NOT NULL,
    username VARCHAR(18) NOT NULL,
    image_id INT REFERENCES images(id) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
